const { Router } = require("express");
const authRoutes = require("./auth.routes");
const userRoutes = require("./user.routes");
const uploadRoutes = require("./upload.routes");
const courseRoutes = require("./course.routes");
const flashcardRoutes = require("./flashcard.routes");
const flashcardPublicRoutes = require("./flashcard-public.routes");
const documentRoutes = require("./document.routes");
const settingRoutes = require("./setting.routes");
const packageRoutes = require("./package.routes");
const aiGeminiRoutes = require("./ai-gemini.routes");
const aiChatRoutes = require("./ai-chat.routes");
const registrationAdminRoutes = require("./registration-admin.routes");
const dashboardAdminRoutes = require("./dashboard-admin.routes");
const dashboardRoutes = require("./dashboard.routes");
const enrollmentRoutes = require("./enrollment.routes");
const expertRoutes = require("./expert.routes");
const quizRoutes = require("./quiz.routes");
const quizAttemptRoutes = require("./quiz-attempts.routes");
const paymentRoutes = require("./payment.routes");

const router = Router();

router.use("/auth", authRoutes);
router.use("/user", userRoutes);
router.use("/upload", uploadRoutes);
router.use("/courses", courseRoutes);
router.use("/public/flashcard-sets", flashcardPublicRoutes);
router.use("/flashcard-sets", flashcardRoutes);
router.use("/documents", documentRoutes);
router.use("/settings", settingRoutes);
router.use("/packages", packageRoutes);
router.use("/ai-gemini", aiGeminiRoutes);
router.use("/ai-chat", aiChatRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/enrollments", enrollmentRoutes);
router.use("/experts", expertRoutes);
router.use("/quiz-practices", quizRoutes);
router.use("/quiz-attempts", quizAttemptRoutes);
router.use("/payments", paymentRoutes);
router.use("/admin/registrations", registrationAdminRoutes);
router.use("/admin/dashboard", dashboardAdminRoutes);

module.exports = router;
